"""Theme-aware widget status roles.

The Qt stylesheet generated by ThemeManager owns the actual colors. UI code
sets semantic roles here so status presentation stays reactive when themes
change.
"""
from __future__ import annotations

import re
from typing import Any


_COLOR_RE = re.compile(r"#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})")

_LEGACY_COLOR_ROLES = {
    "#00aa40": "success",
    "#2dd4bf": "success",
    "#4ade80": "success",
    "#88ff88": "success",
    "#2a8c4a": "success",
    "#ccaa00": "warning",
    "#cc8800": "warning",
    "#f59e0b": "warning",
    "#cc3040": "error",
    "#cc3333": "error",
    "#dc3250": "error",
    "#d44": "error",
    "#f43f5e": "error",
    "#f87171": "error",
    "#ff4444": "error",
    "#808898": "muted",
    "#888": "muted",
    "#888888": "muted",
    "#94a3b8": "muted",
    "#aaaaaa": "muted",
    "#6b5d8a": "muted",
    "#4a3a6a": "muted",
    "#8b7ab8": "muted",
    "#c084fc": "accent",
    "#f9a8d4": "accent",
    "#6c3bf5": "accent",
    "#aaddff": "info",
}

_STATE_ROLES = {
    "ready": "success",
    "idle": "success",
    "complete": "success",
    "speaking": "success",
    "listening": "success",
    "online": "success",
    "on": "success",
    "connected": "success",
    "running": "success",
    "booting": "warning",
    "initializing": "warning",
    "connecting": "warning",
    "cooldown": "warning",
    "thinking": "warning",
    "generating": "warning",
    "processing": "warning",
    "interrupted": "warning",
    "partial": "warning",
    "degraded": "warning",
    "error": "error",
    "failed": "error",
    "disconnected": "error",
    "offline": "error",
    "stopped": "error",
    "disabled": "muted",
    "off": "muted",
    "unknown": "muted",
}


def set_status_role(widget: Any, role: str | None) -> None:
    """Apply a semantic status role and repolish the widget."""
    clean_role = str(role or "").strip().lower()
    widget.setProperty("statusRole", clean_role)
    widget.setStyleSheet("")
    _repolish(widget)


def clear_status_role(widget: Any) -> None:
    set_status_role(widget, "")


def apply_status_style(widget: Any, legacy_style: str | None = "", role: str | None = None) -> None:
    """Convert old inline color styles to semantic stylesheet roles."""
    semantic_role = role or role_from_legacy_style(legacy_style)
    set_status_role(widget, semantic_role or "")


def role_from_state(state: str | None) -> str:
    normalized = str(state or "").split("|", 1)[0].strip().lower()
    return _STATE_ROLES.get(normalized, "muted")


def role_from_legacy_style(style: str | None) -> str:
    raw = str(style or "").strip().lower()
    if raw in _LEGACY_COLOR_ROLES:
        return _LEGACY_COLOR_ROLES[raw]
    match = _COLOR_RE.search(raw)
    if not match:
        return ""
    return _LEGACY_COLOR_ROLES.get(match.group(0).lower(), "")


def _repolish(widget: Any) -> None:
    style = widget.style()
    style.unpolish(widget)
    style.polish(widget)
    widget.update()
